# Generated by Django 4.2.3 on 2023-08-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MultifunctionalDevice',
            fields=[
                ('voucher_numberm', models.CharField(blank=True, db_column='Voucher_Number', default=None, max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, db_column='Brand_Name', max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, db_column='Model_Name', max_length=50, null=True)),
                ('grant', models.CharField(blank=True, db_column='Grant', max_length=50, null=True)),
                ('purchaseyear', models.CharField(blank=True, db_column='Year_Of_Purchase', max_length=4, null=True)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=50, null=True)),
                ('nomenclature', models.CharField(blank=True, db_column='Nomenclature', max_length=250, null=True)),
            ],
            options={
                'db_table': 'multifunctional_device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('voucher_numberp', models.CharField(blank=True, db_column='Voucher_Number', default=None, max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, db_column='Brand_Name', max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, db_column='Model_Name', max_length=50, null=True)),
                ('grant', models.CharField(blank=True, db_column='Grant', max_length=50, null=True)),
                ('pyop', models.CharField(blank=True, db_column='Year_Of_Purchase', max_length=4, null=True)),
                ('ptype', models.CharField(blank=True, db_column='Printer_Type', max_length=50, null=True)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=50, null=True)),
                ('nomenclature', models.CharField(blank=True, db_column='Nomenclature', max_length=250, null=True)),
            ],
            options={
                'db_table': 'printer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('voucher_numberu', models.CharField(blank=True, db_column='Voucher_Number', default=None, max_length=50, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, db_column='Brand_Name', max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, db_column='Model_Name', max_length=50, null=True)),
                ('grant', models.CharField(blank=True, db_column='Grant', max_length=50, null=True)),
                ('uyop', models.CharField(blank=True, db_column='Year_Of_Purchase', max_length=4, null=True)),
                ('ups_power', models.CharField(blank=True, db_column='UPS_Power', max_length=50, null=True)),
                ('ups_type', models.CharField(blank=True, db_column='UPS_Type', max_length=50, null=True)),
                ('group', models.CharField(blank=True, db_column='Group', max_length=50, null=True)),
                ('nomenclature', models.CharField(blank=True, db_column='Nomenclature', max_length=250, null=True)),
            ],
            options={
                'db_table': 'ups',
                'managed': True,
            },
        ),
    ]
